F
======================================================================
FAIL: test_eval_1 (__main__.TestNetflix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "TestNetflix.py", line 27, in test_eval_1
    w.getvalue(), "10040:\n2.4\n2.4\n2.4\n0.90\n")
AssertionError: '10040:\n2.4\n2.4\n2.4\nRMSE: 0.90\n' != '10040:\n2.4\n2.4\n2.4\n0.90\n'
  10040:
  2.4
  2.4
  2.4
- RMSE: 0.90
+ 0.90


----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
